// Mocks generated by Mockito 5.4.6 from annotations
// in im_sdkui/test/im_sdkui_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:im_sdk_api/src/auth/auth_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRegisterCredential_0 extends _i1.SmartFake
    implements _i2.RegisterCredential {
  _FakeRegisterCredential_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthService extends _i1.Mock implements _i2.IAuthService {
  MockIAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasLoginToken =>
      (super.noSuchMethod(Invocation.getter(#hasLoginToken), returnValue: false)
          as bool);

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  _i3.Future<_i2.LoginResult> login(
    String? countryCode,
    String? phone,
    String? password, {
    String? selectedUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #login,
              [countryCode, phone, password],
              {#selectedUserId: selectedUserId},
            ),
            returnValue: _i3.Future<_i2.LoginResult>.value(
              _i4.dummyValue<_i2.LoginResult>(
                this,
                Invocation.method(
                  #login,
                  [countryCode, phone, password],
                  {#selectedUserId: selectedUserId},
                ),
              ),
            ),
          )
          as _i3.Future<_i2.LoginResult>);

  @override
  _i3.Future<_i2.RegisterCredential> register(
    String? countryCode,
    String? phone,
    String? password,
    String? nickname,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [
              countryCode,
              phone,
              password,
              nickname,
            ]),
            returnValue: _i3.Future<_i2.RegisterCredential>.value(
              _FakeRegisterCredential_0(
                this,
                Invocation.method(#register, [
                  countryCode,
                  phone,
                  password,
                  nickname,
                ]),
              ),
            ),
          )
          as _i3.Future<_i2.RegisterCredential>);

  @override
  _i3.Future<void> autoLogin() =>
      (super.noSuchMethod(
            Invocation.method(#autoLogin, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
